---

- hosts: all
  become: true
  tasks:


  - name: update repo
    yum:
      update_cache: yes


  - name: add php support
    yum:
      name: epel-release

  - name: php install
    yum:
      name: php
