---

- hosts: all
  become: true
  tasks:


  - name: update repo
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: add php support
    apt:
      name: epel-release
      state: absent
    when: ansible_distribution == "Ubuntu"


  - name: php install
    apt:
      name: php
      state: absent
    when: ansible_distribution == "Ubuntu"

